name: Lint

on: [push]

jobs:
  build:
    runs-on:  ubuntu-24.04

    steps:
    - uses: actions/checkout@v2
    - uses: astral-sh/setup-uv@v7

    - name: Install prerequisites
      run: |
        sudo apt update
        sudo apt install --yes libcairo2-dev libgirepository-2.0-dev

    - name: Install dependencies
      run: uv sync

    - name: Lint
      run: |
        uv run ruff check
        uv run mypy
